Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,8 +17,7 @@ jobs:
         run: |
           echo "Building the project"
           echo "Build completed successfully."
-          exit 1
-          echo "status=success" >> $GITHUB_ENV
+          exit 1  # Simulating a failure for testing
 
   overall_status:
     runs-on: ubuntu-latest
@@ -47,9 +46,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: overall_status
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
-
       - name: Send Notifications
         uses: ./.github/actions/notify_teams  # Path to your composite action
         with:
